#
# Test data for Tori.
# SQL clauses cannot span over multiple lines.
#
# Categories
insert into CATEGORY set ID = 1, NAME = "News & Announcements", DESCRIPTION = "All news and announcements.", DISPLAYORDER = 0;
insert into CATEGORY set ID = 2, NAME = "Using the Forums", DESCRIPTION = "Guidelines and tips for using the forums.", DISPLAYORDER = 1;
insert into CATEGORY set ID = 3, NAME = "Vaadin Discussion", DESCRIPTION = "All Vaadin related discussion.", DISPLAYORDER = 2;
insert into CATEGORY set ID = 4, NAME = "Git Discussion", DESCRIPTION = "All Git related discussion.", DISPLAYORDER = 3;

# SubCategories
insert into CATEGORY set ID = 5, PARENTCATEGORY_ID = 1, NAME = "News", DESCRIPTION = "All news.", DISPLAYORDER = 0;
insert into CATEGORY set ID = 6, PARENTCATEGORY_ID = 1, NAME = "Announcements", DESCRIPTION = "All announcements.", DISPLAYORDER = 1;

# Threads
insert into DISCUSSIONTHREAD set ID = 1, CATEGORY_ID = 5, TOPIC = "Tori alpha 1 released";
insert into DISCUSSIONTHREAD set ID = 2, CATEGORY_ID = 2, TOPIC = "Writing new messages";
insert into DISCUSSIONTHREAD set ID = 3, CATEGORY_ID = 3, TOPIC = "Issues with widgetset compilation";
insert into DISCUSSIONTHREAD set ID = 4, CATEGORY_ID = 4, TOPIC = "What does 'git rebase' actually do";
insert into DISCUSSIONTHREAD set ID = 5, CATEGORY_ID = 6, TOPIC = "Announced the future release date of Tori alpha 2";
insert into DISCUSSIONTHREAD set ID = 6, CATEGORY_ID = 5, TOPIC = "Something new is happening";
insert into DISCUSSIONTHREAD set ID = 7, CATEGORY_ID = 3, TOPIC = "How to deploy Vaadin applications to Liferay";
insert into DISCUSSIONTHREAD set ID = 8, CATEGORY_ID = 3, TOPIC = "How to change the color of a Label";

## Users
insert into `USER` set ID = 1, DISPLAYEDNAME = "John Doe";
insert into `USER` set ID = 2, DISPLAYEDNAME = "Molly Townsend";

## Posts
insert into POST set ID = 1, `TIME` = "2011-10-1 12:00:00", THREAD_ID = 1, AUTHOR_ID = 1, body = "Nisi ut tempor, jerky ad spare ribs ut ground round labore non sed swine ham. Cupidatat t-bone turducken eu sunt. Ut spare ribs fatback eiusmod ribeye ham consequat prosciutto qui. Tri-tip tail filet mignon, qui jowl consectetur nostrud shankle ut ground round in dolor leberkäse ad. Brisket ex flank bacon dolore prosciutto ut. Nisi dolore fatback, prosciutto meatball kielbasa rump tri-tip consectetur salami pig shoulder. Beef ribs magna shoulder, jerky sunt brisket turducken drumstick tempor nisi eiusmod elit.";
insert into POST set ID = 2, `TIME` = "2011-10-2 12:00:00", THREAD_ID = 1, AUTHOR_ID = 2, body = "Magna turkey minim, in eiusmod turducken beef ribs hamburger tri-tip capicola short loin meatball quis occaecat. Dolore enim biltong pork belly, ea prosciutto consectetur. Dolore ullamco prosciutto venison, sint pig laboris t-bone brisket swine qui. Bresaola tail ham strip steak biltong magna laborum, culpa ex chuck swine. T-bone et ea magna, short loin dolor ut tongue sirloin flank frankfurter in tail pig. Bresaola velit salami, corned beef officia meatloaf cillum spare ribs culpa est leberkäse laboris boudin laborum elit. Cupidatat irure id ham, tongue mollit ad swine velit fugiat.";
insert into POST set ID = 3, `TIME` = "2011-10-1 12:00:00", THREAD_ID = 2, AUTHOR_ID = 1, body = "Nostrud short loin spare ribs kielbasa cupidatat shankle. Anim enim shoulder fatback meatloaf, kielbasa voluptate laborum biltong venison. Laborum esse aliquip, qui irure leberkäse dolore sed labore prosciutto et. Cillum eiusmod in kielbasa, flank non sirloin in laboris. Biltong ad consectetur est commodo, elit voluptate pork loin excepteur spare ribs sirloin kielbasa pig swine. Meatball in sint, tempor est short loin dolore. Pig fugiat eiusmod tri-tip, pastrami meatloaf salami duis pork magna.";
insert into POST set ID = 4, `TIME` = "2011-10-2 12:00:00", THREAD_ID = 2, AUTHOR_ID = 2, body = "Magna elit filet mignon, turducken ad prosciutto adipisicing beef in pastrami chicken. Pork chop cow veniam in aliquip ex. Voluptate ut laborum sausage fugiat. Flank pork reprehenderit excepteur, beef labore sed boudin anim tongue t-bone tenderloin. Hamburger veniam rump chuck. Andouille pork ham hock pork chop tongue. Frankfurter dolore biltong shankle turducken.";
insert into POST set ID = 5, `TIME` = "2011-10-1 12:00:00", THREAD_ID = 3, AUTHOR_ID = 1, body = "Tenderloin prosciutto flank, cupidatat proident jowl nulla brisket shankle laborum irure. Ribeye pig voluptate tail sirloin. Nulla ut nostrud, bacon shoulder short loin shank beef cillum pig. Eiusmod boudin dolore duis, pancetta excepteur turducken incididunt. Ground round strip steak chuck magna enim filet mignon. Magna fugiat sirloin consequat ut. Nulla pork belly ribeye, flank deserunt ham hock kielbasa qui eiusmod short loin exercitation do aute sirloin non.";
insert into POST set ID = 6, `TIME` = "2011-10-2 12:00:00", THREAD_ID = 3, AUTHOR_ID = 2, body = "Bacon cow shankle frankfurter pork. Jowl pork tongue, prosciutto spare ribs leberkäse corned beef brisket frankfurter tenderloin andouille hamburger pork loin short loin jerky. Sirloin jowl kielbasa, andouille swine meatloaf beef ribs ground round biltong jerky capicola tail rump pig. Ground round ball tip swine capicola short loin pastrami leberkäse, salami spare ribs t-bone hamburger bresaola. Meatloaf shankle rump bacon short loin. Pork loin t-bone pork chop, strip steak swine turducken rump short ribs boudin pork belly tri-tip tenderloin ribeye jowl cow. Meatball t-bone spare ribs ribeye, pork turducken ham pig bresaola chuck shank kielbasa andouille venison tail.";
insert into POST set ID = 7, `TIME` = "2011-10-1 12:00:00", THREAD_ID = 4, AUTHOR_ID = 1, body = "Bacon pig frankfurter t-bone shankle. Turkey jerky shoulder swine short loin jowl. Chicken salami shoulder swine short loin. Pork loin brisket pig shank, swine ground round chicken pastrami shoulder salami meatball strip steak spare ribs ball tip. Tri-tip ham prosciutto jerky rump short loin. Tri-tip fatback ground round bresaola, beef shank capicola cow pancetta ham ball tip short loin frankfurter. Leberkäse tri-tip filet mignon tongue corned beef.";
insert into POST set ID = 8, `TIME` = "2011-10-2 12:00:00", THREAD_ID = 4, AUTHOR_ID = 2, body = "Flank bacon brisket, cow prosciutto tenderloin short ribs swine pork chop. Ball tip bresaola pig, jerky venison tongue shank ham hock ham tenderloin turkey turducken. Leberkäse shoulder jerky prosciutto, rump venison pig shankle. Sausage ribeye brisket, fatback meatloaf pork belly turducken chicken pancetta shankle andouille frankfurter. Shank pig turducken cow, kielbasa ball tip drumstick spare ribs boudin ribeye strip steak salami shankle pork chop. Corned beef venison cow, rump jowl short loin boudin turducken fatback turkey pork chop pork. Swine t-bone filet mignon beef rump tri-tip drumstick, brisket short loin.";
insert into POST set ID = 9, `TIME` = "2011-10-4 12:00:00", THREAD_ID = 5, AUTHOR_ID = 2, body = "Fatback corned beef turducken salami pork belly strip steak. Pig boudin meatball bresaola chicken tail. Shankle pig venison ground round. Pork chop meatball pastrami, turkey capicola ham hock pig boudin short loin tongue pork belly sirloin jerky tail. Tail shank ground round filet mignon frankfurter. Meatball jowl capicola, shoulder fatback sausage t-bone tail short loin. Ball tip shankle chuck meatball short ribs turducken, drumstick cow pork loin pastrami tenderloin pork shank tri-tip meatloaf.";
insert into POST set ID = 10, `TIME` = "2011-10-4 12:00:00", THREAD_ID = 6, AUTHOR_ID = 2, body = "Short loin swine ball tip brisket beef ribs, bacon pancetta chuck ribeye filet mignon pork chop pork corned beef andouille pastrami. Drumstick sirloin turkey ribeye. Corned beef fatback chicken short ribs spare ribs, meatball leberkäse ball tip sirloin biltong hamburger short loin jerky bresaola prosciutto. Tail brisket ham strip steak. Andouille short ribs bresaola venison biltong meatball. Bresaola pork chop pancetta pork belly chicken fatback. Bacon fatback brisket, kielbasa pig tri-tip ribeye shankle flank.";
insert into POST set ID = 11, `TIME` = "2011-10-4 12:00:00", THREAD_ID = 7, AUTHOR_ID = 2, body = "Jerky turducken sirloin, beef flank shank bacon capicola. Ham hock tail ribeye pancetta turducken, chicken capicola pork chop swine leberkäse. Pork pork belly cow, sirloin ham hock tail hamburger filet mignon. Sausage turkey salami shankle cow, strip steak pork. Hamburger drumstick short ribs, t-bone pork loin frankfurter capicola pork belly rump ham beef ribs tongue cow jowl. Biltong pork loin cow, pastrami chicken shankle meatloaf sausage pig tri-tip drumstick t-bone fatback pork chop kielbasa. Flank shoulder pork chop, tri-tip shank tongue strip steak frankfurter short ribs pig tenderloin swine brisket bresaola tail.";
insert into POST set ID = 12, `TIME` = "2011-10-5 12:00:00", THREAD_ID = 8, AUTHOR_ID = 2, body = "Short ribs pancetta rump, drumstick beef pork loin beef ribs pastrami kielbasa brisket chuck tri-tip pig. Beef biltong ribeye drumstick. Capicola tail brisket ball tip frankfurter t-bone. Corned beef filet mignon beef chuck, leberkäse ham shankle venison pastrami. Jowl t-bone pork chop, sirloin drumstick beef ham leberkäse ball tip prosciutto sausage chicken tri-tip. Pancetta pig tail, pork chop fatback pork shoulder. Beef ribs beef tenderloin, short ribs drumstick corned beef pork loin venison ball tip tri-tip t-bone tail kielbasa bacon chicken.";
